require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  SuggestExtensions: false
  NewCops: enable

Style/Documentation:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 50

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/MethodLength:
  Max: 25

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false

Layout/LineLength:
  Max: 220

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false

Rails/Pluck:
  Enabled: false
